var imgArr=[
	'img/page1_bc.png',
	'img/page1_land.png',
	'img/page1_door.png',
	'img/page1_light.png',
	'img/page1_kenan.png',
	'img/logo.png',
	'img/share.jpg',
	'img/logo_kenan.png',
	'img/logo_new.png',
	'img/page1_btn.png',
	'img/page1_btn1.png',
	'img/page1_menu_btn.png',
	'img/page1_share_btn.png',
	'img/share_fu_p.png',
	'img/share_fu_pic.png',
	'img/share_fu_pic1.png',
	'img/share_word1.png',
	'img/page1_fu_bc.png',
	'img/page1_fu_close.png',
	'img/page1_menu_inner_bc.jpg',
	'img/page1_menu_on1.png',
	'img/page1_menu_on2.png',
	'img/page1_menu_on3.png',
	'img/page1_menu_on4.png',
	'img/page1_menu_on5.png',
	'img/page1_menu_on6.png',
	'img/page1_tang_c.png',
	'img/page1_tang_l.png',
	'img/page1_tang_r.png',
	'img/page1_user.png',
	'img/page1_user_kuang.png',
	'oimg/page1_menu_on1.png',
	'oimg/page1_menu_on2.png',
	'oimg/page1_menu_on3.png',
	'oimg/page1_menu_on4.png',
	'oimg/page1_menu_on5.png',
	'oimg/page1_menu_on6.png',
	'img/draw.gif',
	'img/game_time.png',
	'img/game1_pic_mark.png',
	'img/game1_pic1_l.jpg',
	'img/game1_pic1_r.jpg',
	'img/game1_pic2_l.jpg',
	'img/game1_pic2_r.jpg',
	'img/game1_pic3_l.jpg',
	'img/game1_pic3_r.jpg',
	'img/game1_pic4_l.jpg',
	'img/game1_pic4_r.jpg',
	'img/game1_pic5_l.jpg',
	'img/game1_pic5_r.jpg',
	'img/game1_pic6_l.jpg',
	'img/game1_pic6_r.jpg',
	'img/game1_pic7_l.jpg',
	'img/game1_pic7_r.jpg',
	'img/game1_pic8_l.jpg',
	'img/game1_pic8_r.jpg',
	'img/game1_pic9_l.jpg',
	'img/game1_pic9_r.jpg',
	'img/game3_card_back.jpg',

	'img/page3_prize1.png',
	'img/page3_prize2.png',
	'img/page3_prize3.png',
	'img/page3_prize4.png',
	'img/game_t_j1.png',
	'img/game_t_j2.png',
	'img/game_t_j3.png',

	'img/game2_bc1.png',
	'img/game2_bc2.png',
	'img/game2_bc3.png',
	'img/game2_camera1.png',
	'img/game2_camera2.png',
	'img/game2_camera3.png',
	'img/game2_p1.png',
	'img/game2_p2.png',
	'img/game2_p3.png',
	'img/game2_p4.png',
	'img/game3_bc.png',
	'img/page_game_bc.png',
	'img/page2_bc.png',
	'img/page2_bc1.png',
	'img/page2_bc2.png',
	'img/page2_bc3.png',
	'img/page2_tan_fra.png',
	'img/page2_tan_fra1.png',
	'img/page3_conan.png',
	'img/page3_luopan_btn.png',
	'img/page3_luopan_point.png',
	'img/page3_prize_fail.png',
	'img/page3_prize_list.png',
	'img/page3_tan_btn.png',
	'img/page3_tan_btn2.png',

	'img/page3_tan_fra_b.png',

	'img/page3_title.png',
	'img/page4_bc.png',
	'img/page5_ban.png',
	'img/page5_bc.png',
	'img/page5_bc1.png',
	'img/page5_bc2.png',
	'img/page5_bc3.png',
	'img/page5_p1_con.png',
	'img/page5_p2_con.png',
	'img/page5_p3_con.png',
	'img/page5_p4_con.png',
	'img/page6_ban.png',
	'img/page6_bc1.png',
	'img/page6_bc2.png',
	'img/page6_bc3.png',
	'img/page6_conan.png',
	'img/page6_game_conan.png',
	'img/page6_game_s.png',
	'img/page6_game_t1.png',
	'img/page6_game_t2.png',
	'img/page6_game1_sword.png',
	'img/page6_game1_tword.png',
	'img/page6_game1_word.png',
	'img/page6_game2_sword.png',
	'img/page6_game2_tword.png',
	'img/page6_game2_word.png',
	'img/page6_game3_sword.png',
	'img/page6_game3_tword.png',
	'img/page6_game3_tword1.png',
	'img/page6_game3_tword2.png',
	'img/page6_game3_word.png',
	'img/page7_bc.png',
	'img/page7_bc1.png',
	'img/page7_bc2.png',
	'img/page8_bc.png',
	'img/page8_bc1.png',
	'img/page8_bc2.png',
	'img/page8_bc3.png',
	'img/personal_ban.png',
	'img/personal_ma.png',
	'img/personal_none_prize.png',
	'img/personal_tan_fra.png',
	'img/personal_tianxie.png',
	'img/prize_list_head.png',
	'img/rule_ban.png',
	'img/rule_tab_bc1.png',
	'img/rule_tab_bc2.png',
	'img/rule_tab_word1.png',
	'img/rule_tab_word2.png',
	'img/rule_word.jpg',
	'img/card/card (1).jpg',
	'img/card/card (2).jpg',
	'img/card/card (3).jpg',
	'img/card/card (4).jpg',
	'img/card/card (5).jpg',
	'img/card/card (6).jpg',
	'img/card/card (7).jpg',
	'img/card/card (8).jpg',
	'img/card/card (9).jpg',
	'img/card/card (10).jpg',
	'img/card/card (11).jpg',
	'img/card/card (12).jpg',
	'img/card/card (13).jpg',
	'img/card/card (14).jpg',
	'img/card/card (15).jpg',
	'img/card/card (16).jpg',
	'img/card/card (17).jpg',
	'img/card/card (18).jpg',
	'img/luo/1.jpg',
	'img/luo/2.jpg',
	'img/luo/3.jpg',
	'img/luo/4.jpg',
	'img/luo/5.jpg',
	'img/luo/6.jpg',
	'img/luo/7.jpg',
	'img/luo/8.jpg',
	'img/luo/9.jpg',
	'img/luo/10.jpg',
	'oimg/page1_menu_on1.png',
	'oimg/page1_menu_on2.png',
	'oimg/page1_menu_on3.png',
	'oimg/page1_menu_on4.png',
	'oimg/page1_menu_on5.png',
	'oimg/page1_menu_on6.png',
]